apiVersion: v1  # Specifies the API version used for the ConfigMap resource
kind: ConfigMap  # The type of resource, which in this case is ConfigMap for storing configuration data
metadata:  # Metadata about the ConfigMap
  name: loki-config  # The name of the ConfigMap being created
  namespace: monitoring-namespace  # The namespace where this ConfigMap will be created
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      wal:
        enabled: true
        dir: /var/loki/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    compactor:
      working_directory: /var/loki/compactor
      shared_store: filesystem
