apiVersion: v1  # Specifies the API version for the PersistentVolume (PV) resource
kind: PersistentVolume  # Defines the resource as a PersistentVolume
metadata:
  name: loki-pv  # The name of the PersistentVolume
spec:
  capacity:
    storage: 200Mi  # The storage capacity of the PersistentVolume (200 MiB)
  accessModes:
    - ReadWriteOnce  # The access mode for the PV (can be mounted as read-write by a single node)
  persistentVolumeReclaimPolicy: Retain  # The reclaim policy, specifies what happens when the PV is released (Retain means keep the data)
  storageClassName: microk8s-hostpath  # The storage class to which this PV belongs (used for dynamic provisioning)
  hostPath:
    path: "/mnt/data/loki"  # The path on the host filesystem where the data is stored
