apiVersion: v1  # Specifies the API version used for the Service resource
kind: Service  # The type of resource, which in this case is Service for exposing network access to a set of Pods
metadata:  # Metadata about the Service
  name: loki  # The name of the Service being created
  namespace: monitoring-namespace  # The namespace where this Service will be created
spec:  # Specifications for the Service
  selector:  # Defines how the Service selects which Pods to route traffic to
    app: loki  # The Service will route traffic to Pods with the label 'app: loki'
  ports:  # Specifies the ports exposed by the Service
    - protocol: TCP  # The protocol used for communication (TCP in this case)
      port: 3100  # The port on which the Service will be exposed
      targetPort: 3100  # The port on the Pods to which traffic is forwarded (should match the container's exposed port)
