apiVersion: v1  # Specifies the API version for the Service resource
kind: Service  # Defines the resource as a Service
metadata:
  name: loki-service  # The name of the Service
  namespace: my-monitoring  # The namespace where the Service is created
spec:
  selector:
    app: loki  # Selector to match pods with the label 'app: loki'
  ports:
    - protocol: TCP  # The protocol used for communication (TCP)
      port: 3100  # The port on which the service will be exposed
      targetPort: 3100  # The port on the container to which traffic will be directed
