apiVersion: v1  # Specifies the API version being used
kind: Secret  # Defines the resource type as a Secret
metadata: # Metadata section for the resource
  name: mysql-secret  # The name of the secret
  namespace: wordpress  # The namespace in which this secret is created
type: Opaque  # Specifies that the secret contains arbitrary data (opaque)
data: # Section containing the actual secret data
  mysql-root-password: cm9vdHBhc3M=  # The MySQL root password encoded in base64
