apiVersion: v1  # Specifies the API version being used
kind: PersistentVolumeClaim  # Defines the resource type as a PersistentVolumeClaim
metadata:  # Metadata section for the resource
  name: wp-pvc  # The name of the PersistentVolumeClaim
  namespace: wordpress  # The namespace in which this PersistentVolumeClaim is created
spec:  # Specification section for the PersistentVolumeClaim
  accessModes:  # Defines the access modes for the persistent volume
    - ReadWriteOnce  # Specifies that the volume can be mounted as read-write by a single node
  resources:  # Defines the resources requested for the persistent volume
    requests:  # Requested resources
      storage: 5Gi  # The amount of storage requested (5 GiB)
