apiVersion: v1  # Specifies the API version being used for the resource
kind: ConfigMap  # Defines the type of resource, which is a ConfigMap
metadata:  # Contains metadata about the resource
  name: busybox-configmap  # The name of the ConfigMap
  namespace: busybox-namespace  # Specifies the namespace where the ConfigMap is created
data:  # Contains the data stored in the ConfigMap
  log_filename: "container.log"  # The key-value pair stored in the ConfigMap, with the key 'log_filename' and its value 'container.log'
