apiVersion: v1  # Specifies the Kubernetes API version
kind: PersistentVolume  # Defines the resource as a PersistentVolume (PV)
metadata:
  name: busybox-pv  # The name of the PersistentVolume
spec:
  capacity:
    storage: 200Mi  # Specifies the storage capacity of the volume (200 MiB)
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # Retains the volume even after the PVC is deleted
  storageClassName: microk8s-hostpath  # The storage class associated with this PV
  hostPath:
    path: "/mnt/data/busybox-pv"  # The path on the host machine where data is stored
