apiVersion: v1  # Specifies the Kubernetes API version
kind: PersistentVolumeClaim  # Defines the resource as a PersistentVolumeClaim (PVC)
metadata:
  name: busybox-pvc  # The name of the PersistentVolumeClaim
  namespace: my-busybox  # The namespace where the PVC is created
spec:
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 200Mi  # The amount of storage requested (200 MiB)
  storageClassName: microk8s-hostpath  # The storage class to be used for binding the PVC to a PV
