apiVersion: v1  # Specifies the API version for the ConfigMap resource
kind: ConfigMap  # Defines the resource as a ConfigMap
metadata:
  name: prometheus-configmap  # The name of the ConfigMap
  namespace: my-monitoring  # The namespace where the ConfigMap is created
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - targets: ['localhost:9100']
          - targets: ['node-exporter-service.my-monitoring.svc.cluster.local:9100']
