apiVersion: v1  # Specifies the API version for managing persistent volume claims
kind: PersistentVolumeClaim  # Defines the resource type as a PersistentVolumeClaim
metadata:  # Metadata section for the PersistentVolumeClaim
  name: {{ .Release.Name }}-wp-pvc  # The name of the PersistentVolumeClaim, dynamically set based on the release name
spec:  # Specification section for the PersistentVolumeClaim
  accessModes:  # List of access modes for the persistent volume
    - ReadWriteOnce  # Allows the volume to be mounted as read-write by a single node
  resources:  # Resource requests for the persistent volume
    requests:
      storage: {{ .Values.wordpress.persistence.size }}  # The amount of storage requested for the volume, set from values
