apiVersion: apps/v1  # Specifies the API version used for the Deployment resource
kind: Deployment  # The type of resource, which in this case is Deployment for managing a set of replica Pods
metadata:  # Metadata about the Deployment
  name: grafana  # The name of the Deployment being created
  namespace: monitoring-namespace  # The namespace where this Deployment will be created
spec:  # Specifications for the Deployment
  replicas: 1  # Specifies the number of replicas (Pods) to be created; here it’s 1
  selector:  # Defines how the Deployment finds which Pods to manage
    matchLabels:  # The Deployment will manage Pods with this label
      app: grafana  # Label selector to match Pods with the label 'app: grafana'
  template:  # Template for the Pods created by this Deployment
    metadata:  # Metadata about the Pod
      labels:  # Labels assigned to the Pod
        app: grafana  # The label 'app: grafana' is applied to the Pod
    spec:  # Specifications for the Pod
      containers:  # List of containers within the Pod
        - name: grafana  # The name of the container
          image: grafana/grafana  # The Docker image for the Grafana container
          ports:  # List of ports exposed by the container
            - containerPort: 3000  # Exposes port 3000 for the Grafana service
