apiVersion: v1  # Specifies the API version for the Service resource
kind: Service  # Defines the resource as a Service
metadata:
  name: grafana-service  # The name of the Service
  namespace: my-monitoring  # The namespace where the Service is deployed
spec:
  selector:
    app: grafana  # Selects the pods with the label 'app=grafana' to route traffic to
  ports:
    - protocol: TCP  # The protocol used for communication (TCP in this case)
      port: 30000  # The port exposed by the Service on the cluster
      targetPort: 3000  # The port on the Grafana container to which traffic is forwarded (Grafana's default port)
      nodePort: 30000  # The port exposed on each node in the cluster to access the Service externally
  type: NodePort  # The type of Service, which exposes the Service on a static port on each node
